language: php
php:
  - "5.5"
branches:
  only:
    - master
before_install:
  - composer install
  - npm install
  - bundle install
  - mkdir www
install: ./vendor/pawka/phrozn/bin/phr.php build src && grunt prod
script: true
