--- # Site configuration
path_delimiter: /
imagepath: media/images
entries:
    layout: default.twig

# Files to skip - list of preg expressions is expected
# These are matched against the whole path of the files
skip: [/\.swp$/, /\.bak$/, /\.DS_Store$/, /\.js$/]

# Folders and files to copy without processing
# Note that `media` will be copied regardless of this option,
# as long as we don't want to break BC (v0.6 ?)
copy: [media, favicon.ico]
site:
  output: www
